spring:
  application:
    name: agente-sql

  # Configuración de la API de Gemini
  ai:
    google:
      genai:
        api-key: { GEMINI_API_KEY_PROJECT }
        chat:
          options:
            model: gemini-3.8-flash

  # Conexión a PostgreSQL en Docker
  datasource:
    url: jdbc:postgresql://localhost:5432/educa_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  # Configuración específica de JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas si usas entidades @Entity
    show-sql: true     # Muestra las consultas en la consola de Spring Boot
    properties:
      hibernate:
        format_sql: true